#!/bin/bash
#PBS -N MACE
#PBS -l select=1:ncpus=36:ompthreads=36:ngpus=1:mem=220gb
#PBS -l walltime=24:00:00
#PBS -P CFP03-CF-029
#PBS -P CFP03-SF-106 
#PBS -q auto

module load Anaconda3/2023.09-0
source activate mace
module load iimkl/2023b CMake/3.27.6-GCCcore-13.2.0 CUDA/12.6.0 OpenMPI/4.1.6-GCC-13.2.0
#module load intel/2025.1.3
#module load lapack/3.11-intel
#export PATH=/home/users/nus/zhongpc/scratch/zzh/airss-0.9.1/bin:$PATH

cd $PBS_O_WORKDIR

python mace_SS_airss.py  > MACE.log

