#!/bin/bash
#PBS -N MACE
#PBS -l select=1:ncpus=16:mpiprocs=16:ngpus=1:mem=128gb
#PBS -j oe
#PBS -l walltime=48:00:00 
#PBS -P CFP03-CF-029
#PBS -P CFP03-SF-106
#PBS -q auto

export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
export OMP_NUM_THREADS=1
module load Anaconda3/2023.09-0
module load cuda12.9/
source activate mace

cd ${PBS_O_WORKDIR}

nvidia-smi

mace_run_train --config finetune.yaml
